// ==UserScript==
// @name         Mudae Gallery Copier
// @namespace    local.mhp.mudae-gallery-copier
// @version      1.2.3
// @description  Copies Mudae character gallery/cover image URLs and can bridge results back to Mudae Harem Organizer through Tampermonkey.
// @author       ChatGPT / OpenAI
// @match        https://mudae.net/*
// @match        https://www.mudae.net/*
// @match        file:///*
// @match        http://localhost/*
// @match        http://127.0.0.1/*
// @match        https://*.github.io/*
// @grant        GM_setClipboard
// @grant        GM_setValue
// @grant        GM_getValue
// @grant        GM_addValueChangeListener
// @grant        unsafeWindow
// @run-at       document-start
// ==/UserScript==

/*
  Mudae Gallery Copier v1.2.3
  Generated by ChatGPT / OpenAI for Mudae Harem Organizer.

  What it does:
  - Runs only on Mudae tabs opened by the local Organizer marker.
  - Copies gallery image URLs from section#images.
  - Falls back to section#intro / #cover when a character has only one image.
  - Auto-opens the first matching result when Mudae lands on /search first.
  - Preserves Mudae metadata such as image number, tags, artist, rating and data-matches.
  - Produces compact JSON compatible with the Organizer gallery importer.
  - Closes the helper tab after copying.
  - Optional Auto Bridge: when this userscript also runs on the Organizer page,
    it can send gallery results through GM_setValue instead of requiring Ctrl+V.
*/

(function () {
  'use strict';

  const SCRIPT_VERSION = '1.2.3';
  const BRIDGE = {
    key: 'mhp_mudae_gallery_bridge_payload_v1',
    eventName: 'mhp:mudae-gallery-bridge-result',
    readyEventName: 'mhp:mudae-gallery-bridge-ready',
    ttlMs: 10 * 60 * 1000
  };

  function isMudaeHost() {
    const host = String(location.hostname || '').toLowerCase();
    return host === 'mudae.net' || host === 'www.mudae.net';
  }

  function emitOrganizerEvent(name, detail = {}) {
    const target = typeof unsafeWindow !== 'undefined' ? unsafeWindow : window;
    const textDetail = typeof detail === 'string' ? detail : JSON.stringify(detail);

    try {
      target.dispatchEvent(new CustomEvent(name, { detail: textDetail }));
    } catch {
      window.dispatchEvent(new CustomEvent(name, { detail: textDetail }));
    }
  }

  function startOrganizerBridgeReceiver() {
    try {
      const target = typeof unsafeWindow !== 'undefined' ? unsafeWindow : window;
      target.__mhpMudaeGalleryBridgeReady = true;
    } catch {}

    emitOrganizerEvent(BRIDGE.readyEventName, { source: 'mudae-gallery-copier', version: SCRIPT_VERSION });

    const dispatchPayload = value => {
      if (!value) return;

      let wrapper = value;
      if (typeof wrapper === 'string') {
        try { wrapper = JSON.parse(wrapper); } catch { return; }
      }

      if (!wrapper || typeof wrapper !== 'object') return;

      const copiedAt = Date.parse(wrapper.copiedAt || wrapper.receivedAt || 0);
      if (Number.isFinite(copiedAt) && copiedAt > 0 && Date.now() - copiedAt > BRIDGE.ttlMs) return;

      emitOrganizerEvent(BRIDGE.eventName, wrapper);
    };

    try {
      if (typeof GM_addValueChangeListener === 'function') {
        GM_addValueChangeListener(BRIDGE.key, (_key, _oldValue, newValue) => dispatchPayload(newValue));
      }
    } catch {}

    setTimeout(() => {
      try {
        if (typeof GM_getValue === 'function') dispatchPayload(GM_getValue(BRIDGE.key, ''));
      } catch {}
    }, 500);
  }

  if (!isMudaeHost()) {
    startOrganizerBridgeReceiver();
    return;
  }

  const APP_MARKER = {
    storageKey: 'mhp_gallery_copier_active_v1',
    storageTimeKey: 'mhp_gallery_copier_active_time_v1',
    ttlMs: 10 * 60 * 1000
  };

  const TIMING = {
    retryLimit: 90,
    retryDelayMs: 120,
    firstTryDelayMs: 80,
    closeDelayMs: 40,
    fallbackBlankDelayMs: 180,
    routeCheckMs: 500
  };

  const DEBUG = false;

  let copied = false;
  let retryTimer = null;
  let documentObserver = null;
  let imageObserver = null;
  let pendingTry = false;
  let lastHref = location.href;
  let searchRedirecting = false;

  function debug(...args) {
    if (DEBUG) console.info('[Mudae Gallery Copier]', ...args);
  }

  function info(...args) {
    console.info('[Mudae Gallery Copier]', ...args);
  }

  function getHashParams() {
    try {
      return new URLSearchParams(String(location.hash || '').replace(/^#/, ''));
    } catch {
      return new URLSearchParams('');
    }
  }

  function hasOrganizerMarker() {
    try {
      const query = new URLSearchParams(location.search || '');
      const hash = getHashParams();

      return (
        query.get('mhp_auto') === '1' ||
        query.get('mhp_from') === 'local_app' ||
        hash.get('mhp_auto') === '1' ||
        hash.get('mhp_from') === 'local_app'
      );
    } catch {
      return false;
    }
  }

  function rememberMarkedTab(reason) {
    try {
      sessionStorage.setItem(APP_MARKER.storageKey, '1');
      sessionStorage.setItem(APP_MARKER.storageTimeKey, String(Date.now()));
      debug('tab marked via', reason, location.href);
    } catch {}
  }

  function hasRememberedMark() {
    try {
      if (sessionStorage.getItem(APP_MARKER.storageKey) !== '1') return false;

      const markedAt = Number(sessionStorage.getItem(APP_MARKER.storageTimeKey) || 0);
      return !markedAt || Date.now() - markedAt < APP_MARKER.ttlMs;
    } catch {
      return false;
    }
  }

  function isMarkedTab() {
    if (hasOrganizerMarker()) {
      if (!hasRememberedMark()) rememberMarkedTab('url/hash');
      return true;
    }

    return hasRememberedMark();
  }

  function cleanUrl(value) {
    let url = String(value || '').trim();
    if (!url) return '';

    url = url
      .replace(/&amp;/g, '&')
      .replace(/[),.;\]}]+$/g, '')
      .replace(/^["'<]+|[>"']+$/g, '');

    try {
      return new URL(url, location.href).href;
    } catch {
      return url;
    }
  }

  function isUsableImageUrl(url) {
    const lower = String(url || '').toLowerCase();
    if (!lower || lower.startsWith('data:')) return false;

    return (
      /\.(png|jpe?g|webp|gif)(\?|#|$)/i.test(lower) ||
      /mudae\.net\/uploads/i.test(lower) ||
      /cdn\.discordapp\.com|media\.discordapp\.net|discordapp\.com\/attachments/i.test(lower)
    );
  }

  function normalizeText(value) {
    return String(value || '')
      .normalize('NFKD')
      .replace(/[\u0300-\u036f]/g, '')
      .replace(/[{}()[\]_.:;~!?,+\-]+/g, ' ')
      .replace(/\s+/g, ' ')
      .trim()
      .toLowerCase();
  }

  function getSearchTargetName() {
    try {
      const url = new URL(location.href);
      if (!/\/search\/?$/i.test(url.pathname)) return '';
      if ((url.searchParams.get('type') || '').toLowerCase() !== 'character') return '';
      return String(url.searchParams.get('name') || '').trim();
    } catch {
      return '';
    }
  }

  function findCharacterResultLink(targetName) {
    const target = normalizeText(targetName);
    const links = Array.from(document.querySelectorAll('a[href*="/character/"]'));
    if (!links.length) return null;

    const candidates = links
      .map(link => {
        const href = link.getAttribute('href') || '';
        const text = normalizeText(link.textContent || link.getAttribute('title') || link.getAttribute('aria-label') || '');
        let url = null;
        try { url = new URL(href, location.href); } catch {}
        if (!url || !/\/character\/\d+/i.test(url.pathname)) return null;

        const pathName = normalizeText(decodeURIComponent(url.pathname.split('/').pop() || ''));
        let score = 1;
        if (target && text === target) score += 40;
        if (target && pathName === target) score += 35;
        if (target && text.includes(target)) score += 20;
        if (target && pathName.includes(target)) score += 18;
        if (/^https?:\/\/[^/]*mudae\.net$/i.test(url.origin)) score += 2;

        return { link, url, score };
      })
      .filter(Boolean)
      .sort((a, b) => b.score - a.score);

    return candidates[0] || null;
  }

  function preserveOrganizerBridgeParams(url) {
    try {
      const next = new URL(url.href || url, location.href);
      const currentHash = getHashParams();
      const currentQuery = new URLSearchParams(location.search || '');
      const bridgeKeys = ['mhp_auto', 'mhp_from', 'mhp_bridge', 'mhp_queue_id', 'mhp_character_id'];
      const nextHash = new URLSearchParams(String(next.hash || '').replace(/^#/, ''));

      bridgeKeys.forEach(key => {
        const value = currentHash.get(key) || currentQuery.get(key);
        if (value && !nextHash.has(key)) nextHash.set(key, value);
      });

      const hashText = nextHash.toString();
      if (hashText) next.hash = hashText;
      return next;
    } catch {
      return url;
    }
  }

  function maybeOpenSearchResult(attempt = 0) {
    if (copied || searchRedirecting || !isMarkedTab()) return false;

    const targetName = getSearchTargetName();
    if (!targetName) return false;

    const result = findCharacterResultLink(targetName);
    if (result?.url) {
      searchRedirecting = true;
      cleanup();
      const targetUrl = preserveOrganizerBridgeParams(result.url);
      info(`opening search result for "${targetName}" with organizer bridge markers preserved`);
      location.assign(targetUrl.href || result.url.href);
      return true;
    }

    if (attempt < TIMING.retryLimit) {
      clearTimeout(retryTimer);
      retryTimer = setTimeout(() => maybeOpenSearchResult(attempt + 1), TIMING.retryDelayMs);
    } else {
      debug(`marked search page but no character result was found for "${targetName}"`);
    }

    return true;
  }

  function getImagesRoot() {
    return document.querySelector('section#images') || document.getElementById('images');
  }

  function getCoverRoot() {
    return (
      document.querySelector('section#intro #cover') ||
      document.querySelector('section#intro img#cover') ||
      document.querySelector('section#intro .cover') ||
      document.getElementById('cover')
    );
  }

  function getActiveImageRoot() {
    const galleryRoot = getImagesRoot();
    if (galleryRoot) return { root: galleryRoot, mode: 'gallery' };

    const coverRoot = getCoverRoot();
    if (coverRoot) return { root: coverRoot, mode: 'cover' };

    return { root: null, mode: 'none' };
  }

  function imagesFromRoot(root, mode) {
    if (!root) return [];

    if (root.matches?.('img')) return [root];

    if (mode === 'cover') {
      return Array.from(root.querySelectorAll('img#cover, img.charimage, img'));
    }

    return Array.from(root.querySelectorAll('img.charimage, img'));
  }

  function getImageUrl(img) {
    return cleanUrl(
      img?.currentSrc ||
      img?.src ||
      img?.getAttribute?.('src') ||
      img?.getAttribute?.('data-src') ||
      img?.getAttribute?.('data-original') ||
      img?.getAttribute?.('data-lazy-src') ||
      ''
    );
  }

  function decodeHtmlAttribute(value) {
    return String(value || '')
      .replace(/&quot;/g, '"')
      .replace(/&#34;/g, '"')
      .replace(/&#39;/g, "'")
      .replace(/&amp;/g, '&');
  }

  function parseJsonAttribute(value, fallback) {
    const raw = String(value || '').trim();
    if (!raw) return fallback;

    try {
      return JSON.parse(raw);
    } catch {}

    try {
      return JSON.parse(decodeHtmlAttribute(raw));
    } catch {}

    return fallback;
  }

  function toNumber(value, fallback = null) {
    const number = Number(value);
    return Number.isFinite(number) ? number : fallback;
  }

  function normalizeMatch(match) {
    if (!match || typeof match !== 'object') return match;

    const output = { ...match };
    const rawImage = (
      output.url ||
      output.imageUrl ||
      output.src ||
      output.href ||
      output.link ||
      output.image ||
      output.filename ||
      output.file ||
      ''
    );

    if (typeof rawImage !== 'string' || !rawImage.trim()) return output;

    const raw = rawImage.trim().replace(/&amp;/g, '&').replace(/^["']+|["']+$/g, '');

    if (/^https?:\/\//i.test(raw)) {
      output.previewUrl = raw;
      return output;
    }

    if (/mudae\.net\/uploads/i.test(raw)) {
      output.previewUrl = raw.replace(/^\/+/g, 'https://');
      return output;
    }

    if (/\.(?:png|jpe?g|webp|gif)(?:[?#]|$)/i.test(raw)) {
      const ownerId = output.ownerId || output.userId || output.uploadId || output.upload || output.id || '';
      if (ownerId && /^\d+$/.test(String(ownerId))) {
        output.previewUrl = `https://mudae.net/uploads/${ownerId}/${raw.replace(/^\/+/g, '')}`;
      }
    }

    return output;
  }

  function readMatches(img) {
    const raw = img?.getAttribute?.('data-matches') || img?.dataset?.matches || '';
    if (!raw) return [];

    const parsed = parseJsonAttribute(raw, []);
    return Array.isArray(parsed) ? parsed.map(normalizeMatch) : [];
  }

  function cleanMetadataLabel(value) {
    return String(value || '')
      .replace(/[\u201c\u201d]/g, '"')
      .replace(/[\u2018\u2019]/g, "'")
      .trim()
      .replace(/^[\s\[\]"']+/g, '')
      .replace(/[\s\[\]"']+$/g, '')
      .replace(/\s+/g, ' ')
      .trim();
  }

  function normalizeMetadataLabel(value) {
    if (value === null || value === undefined) return '';
    if (typeof value === 'string' || typeof value === 'number') return cleanMetadataLabel(value);
    if (typeof value === 'object') {
      return cleanMetadataLabel(value.label || value.name || value.tag || value.title || value.value || value.text || '');
    }
    return '';
  }

  function expandMetadataLabels(value) {
    const out = [];
    const push = label => {
      const normalized = normalizeMetadataLabel(label);
      if (normalized) out.push(normalized);
    };

    if (value === null || value === undefined) return out;
    if (Array.isArray(value)) {
      value.forEach(entry => expandMetadataLabels(entry).forEach(push));
      return out;
    }
    if (typeof value === 'string') {
      const text = value.trim();
      if (!text) return out;
      if (/^\s*\[/.test(text)) {
        try {
          const parsed = JSON.parse(text);
          if (Array.isArray(parsed)) {
            parsed.forEach(entry => expandMetadataLabels(entry).forEach(push));
            return out;
          }
        } catch {}
      }
      text.replace(/^[\s\[]+|[\s\]]+$/g, '').split(/[,;|]/g).forEach(push);
      return out;
    }
    push(value);
    return out;
  }

  function dedupeMetadataLabels(values) {
    const seen = new Set();
    const out = [];
    expandMetadataLabels(values).forEach(label => {
      const key = cleanMetadataLabel(label).toLowerCase().replace(/\s+/g, ' ').trim();
      if (!key || seen.has(key)) return;
      seen.add(key);
      out.push(cleanMetadataLabel(label));
    });
    return out;
  }

  function readArrayAttribute(img, attrName) {
    const raw = img?.getAttribute?.(attrName) || img?.dataset?.[attrName.replace(/^data-/, '')] || '';
    if (!raw) return [];

    const parsed = parseJsonAttribute(raw, []);
    if (Array.isArray(parsed)) return dedupeMetadataLabels(parsed);
    if (typeof parsed === 'string') return dedupeMetadataLabels(parsed.split(/[,;|]/g));
    return [];
  }

  function readTagsFromText(value) {
    const text = String(value || '').trim();
    if (!text) return [];
    const match = text.match(/tags?\s*[:：]\s*([^\n]+)/i);
    if (!match) return [];
    return dedupeMetadataLabels(match[1]);
  }

  function readImageTags(img) {
    const candidates = [
      ...readArrayAttribute(img, 'data-tags'),
      ...readArrayAttribute(img, 'data-tag'),
      ...readArrayAttribute(img, 'tags')
    ];

    const datasetTags = img?.dataset?.tags || img?.dataset?.tag || '';
    if (datasetTags) candidates.push(...dedupeMetadataLabels(datasetTags));

    const aria = img?.getAttribute?.('aria-label') || img?.getAttribute?.('title') || '';
    candidates.push(...readTagsFromText(aria));

    // Some Mudae cards expose metadata on the closest gallery/image wrapper
    // instead of the <img> itself. Include title/aria wrappers because Mudae
    // sometimes exposes tag information only through hover text.
    const wrapper = img?.closest?.('[data-tags],[data-tag],[title],[aria-label]');
    if (wrapper && wrapper !== img) {
      candidates.push(...readArrayAttribute(wrapper, 'data-tags'));
      candidates.push(...readArrayAttribute(wrapper, 'data-tag'));
      candidates.push(...readTagsFromText(wrapper.getAttribute('title') || wrapper.getAttribute('aria-label') || ''));
    }

    const nearby = img?.closest?.('a,button,figure,li,article,div');
    if (nearby) {
      nearby.querySelectorAll?.('[class*="tag"],[data-tags],[data-tag],[title*="Tag"],[aria-label*="Tag"]').forEach(node => {
        if (node === img) return;
        candidates.push(...readArrayAttribute(node, 'data-tags'));
        candidates.push(...readArrayAttribute(node, 'data-tag'));
        candidates.push(...readTagsFromText(node.getAttribute('title') || node.getAttribute('aria-label') || ''));
        const text = String(node.textContent || '').trim();
        if (text && text.length <= 80 && !/https?:\/\//i.test(text)) candidates.push(...dedupeMetadataLabels(text));
      });
    }

    return dedupeMetadataLabels(candidates);
  }

  function collectGalleryImages() {
    const { root, mode } = getActiveImageRoot();
    if (!root) return [];

    const images = [];
    const seenUrls = new Set();

    for (const img of imagesFromRoot(root, mode)) {
      const url = getImageUrl(img);
      if (!url || !isUsableImageUrl(url)) continue;

      const dedupeKey = url.replace(/[#?].*$/, '');
      if (seenUrls.has(dedupeKey)) continue;
      seenUrls.add(dedupeKey);

      const fallbackNumber = images.length + 1;
      const imageNumber = toNumber(img.getAttribute('data-number') || img.dataset?.number, fallbackNumber);
      const rating = toNumber(img.getAttribute('data-rating') || img.dataset?.rating, null);
      const matches = readMatches(img);

      images.push({
        index: imageNumber || fallbackNumber,
        number: imageNumber || fallbackNumber,
        url,
        id: img.getAttribute('data-id') || img.dataset?.id || '',
        name: img.getAttribute('data-name') || img.dataset?.name || '',
        matched: matches.length > 0,
        matches,
        rating,
        tags: readImageTags(img),
        artist: readArrayAttribute(img, 'data-artist'),
        mode,
        source: 'mudae-gallery-copier-v1.2.3'
      });
    }

    return images;
  }

  function getBridgeContext() {
    const hash = getHashParams();
    const query = new URLSearchParams(location.search || '');

    return {
      enabled: hash.get('mhp_bridge') === '1' || query.get('mhp_bridge') === '1',
      queueId: hash.get('mhp_queue_id') || query.get('mhp_queue_id') || '',
      characterId: hash.get('mhp_character_id') || query.get('mhp_character_id') || ''
    };
  }

  async function publishBridgePayload(payload) {
    const bridge = getBridgeContext();
    if (!bridge.enabled || typeof GM_setValue !== 'function') return false;

    const wrapper = {
      type: 'mhp-mudae-gallery-bridge-result',
      version: 1,
      id: `${Date.now()}-${Math.random().toString(36).slice(2)}`,
      queueId: bridge.queueId,
      characterId: bridge.characterId,
      copiedAt: new Date().toISOString(),
      source: 'mudae-gallery-copier-v1.2.3',
      page: location.href,
      payload
    };

    await GM_setValue(BRIDGE.key, JSON.stringify(wrapper));
    return true;
  }

  function buildPayload(images) {
    return {
      type: 'mhp-mudae-gallery',
      version: 2,
      source: 'mudae-gallery-copier-v1.2.3',
      page: location.href,
      copiedAt: new Date().toISOString(),
      matchedCount: images.filter(image => image.matched).length,
      images
    };
  }

  async function copyText(text) {
    if (typeof GM_setClipboard === 'function') {
      GM_setClipboard(text, 'text');
      return true;
    }

    if (navigator.clipboard?.writeText) {
      await navigator.clipboard.writeText(text);
      return true;
    }

    const textarea = document.createElement('textarea');
    textarea.value = text;
    textarea.setAttribute('readonly', 'readonly');
    textarea.style.position = 'fixed';
    textarea.style.left = '-9999px';
    document.body.appendChild(textarea);
    textarea.select();

    const copiedText = document.execCommand('copy');
    textarea.remove();
    return copiedText;
  }

  function cleanup() {
    clearTimeout(retryTimer);
    retryTimer = null;

    try { documentObserver?.disconnect(); } catch {}
    try { imageObserver?.disconnect(); } catch {}

    documentObserver = null;
    imageObserver = null;
  }

  function closeHelperTab() {
    setTimeout(() => {
      try { window.close(); } catch {}

      setTimeout(() => {
        try {
          if (!document.hidden) location.replace('about:blank');
        } catch {}
      }, TIMING.fallbackBlankDelayMs);
    }, TIMING.closeDelayMs);
  }

  async function tryCopy(attempt = 0) {
    if (copied || !isMarkedTab()) return;
    if (maybeOpenSearchResult(0)) return;

    const images = collectGalleryImages();

    if (!images.length) {
      if (attempt < TIMING.retryLimit) {
        clearTimeout(retryTimer);
        retryTimer = setTimeout(() => tryCopy(attempt + 1), TIMING.retryDelayMs);
      } else {
        debug('marked tab but no gallery/cover image was found after retries');
      }
      return;
    }

    copied = true;
    cleanup();

    try {
      const payload = buildPayload(images);
      const bridged = await publishBridgePayload(payload).catch(error => {
        info('bridge publish failed, falling back to clipboard', error);
        return false;
      });

      if (!bridged) {
        await copyText(JSON.stringify(payload));
      }

      info(`${bridged ? 'bridged' : 'copied'} ${images.length} images, ${payload.matchedCount} matched${bridged ? ', clipboard untouched' : ''}`);
      closeHelperTab();
    } catch (error) {
      copied = false;
      info('copy/bridge failed', error);
    }
  }

  function scheduleCopy(delay = 0) {
    if (copied || pendingTry || !isMarkedTab()) return;

    pendingTry = true;
    setTimeout(() => {
      pendingTry = false;
      tryCopy(0);
    }, delay);
  }

  function start(reason) {
    if (!isMarkedTab()) return;

    debug('active on marked tab:', reason, location.href);
    if (maybeOpenSearchResult(0)) return;
    scheduleCopy(TIMING.firstTryDelayMs);
    setTimeout(() => scheduleCopy(0), 300);
    setTimeout(() => scheduleCopy(0), 700);
    setTimeout(() => scheduleCopy(0), 1200);
  }

  function observeDom() {
    if (documentObserver) return;

    function attachObserver() {
      if (!document.documentElement) {
        setTimeout(attachObserver, 30);
        return;
      }

      documentObserver = new MutationObserver(() => {
        if (copied || !isMarkedTab()) return;

        const { root } = getActiveImageRoot();
        if (!root) return;

        scheduleCopy(30);

        try { documentObserver.disconnect(); } catch {}
        documentObserver = null;

        if (!imageObserver) {
          imageObserver = new MutationObserver(() => scheduleCopy(30));
          imageObserver.observe(root, {
            childList: true,
            subtree: true,
            attributes: true,
            attributeFilter: ['src', 'data-src', 'data-matches']
          });
        }
      });

      documentObserver.observe(document.documentElement, { childList: true, subtree: true });
    }

    attachObserver();
  }

  function watchRouteChanges() {
    setInterval(() => {
      if (location.href === lastHref) return;

      lastHref = location.href;
      copied = false;
      searchRedirecting = false;
      cleanup();
      start('route-change');
      observeDom();
    }, TIMING.routeCheckMs);
  }

  if (hasOrganizerMarker()) rememberMarkedTab('initial-url-or-hash');

  start('document-start');
  observeDom();
  watchRouteChanges();

  window.addEventListener('hashchange', () => start('hashchange'));
  window.addEventListener('DOMContentLoaded', () => start('DOMContentLoaded'));
  window.addEventListener('load', () => start('load'));
})();
