// ==UserScript==
// @name         Mudae Gallery Copier
// @namespace    local.mhp.mudae-gallery-copier
// @version      1.0.2
// @description  Copies Mudae character gallery/cover image URLs and match metadata for Mudae Harem Organizer tabs opened from the local app.
// @author       ChatGPT / OpenAI
// @match        https://mudae.net/*
// @match        https://www.mudae.net/*
// @grant        GM_setClipboard
// @run-at       document-start
// ==/UserScript==

/*
  Mudae Gallery Copier v1.0.2
  Generated by ChatGPT / OpenAI for Mudae Harem Organizer.

  What it does:
  - Runs only on Mudae tabs opened by the local Organizer marker.
  - Copies gallery image URLs from section#images.
  - Falls back to section#intro / #cover when a character has only one image.
  - Auto-opens the first matching result when Mudae lands on /search first.
  - Preserves Mudae metadata such as image number, tags, artist, rating and data-matches.
  - Produces compact JSON compatible with the Organizer gallery importer.
  - Closes the helper tab after copying.
*/

(function () {
  'use strict';

  const APP_MARKER = {
    storageKey: 'mhp_gallery_copier_active_v1',
    storageTimeKey: 'mhp_gallery_copier_active_time_v1',
    ttlMs: 10 * 60 * 1000
  };

  const TIMING = {
    retryLimit: 90,
    retryDelayMs: 120,
    firstTryDelayMs: 80,
    closeDelayMs: 40,
    fallbackBlankDelayMs: 180,
    routeCheckMs: 500
  };

  const DEBUG = false;

  let copied = false;
  let retryTimer = null;
  let documentObserver = null;
  let imageObserver = null;
  let pendingTry = false;
  let lastHref = location.href;
  let searchRedirecting = false;

  function debug(...args) {
    if (DEBUG) console.info('[Mudae Gallery Copier]', ...args);
  }

  function info(...args) {
    console.info('[Mudae Gallery Copier]', ...args);
  }

  function getHashParams() {
    try {
      return new URLSearchParams(String(location.hash || '').replace(/^#/, ''));
    } catch {
      return new URLSearchParams('');
    }
  }

  function hasOrganizerMarker() {
    try {
      const query = new URLSearchParams(location.search || '');
      const hash = getHashParams();

      return (
        query.get('mhp_auto') === '1' ||
        query.get('mhp_from') === 'local_app' ||
        hash.get('mhp_auto') === '1' ||
        hash.get('mhp_from') === 'local_app'
      );
    } catch {
      return false;
    }
  }

  function rememberMarkedTab(reason) {
    try {
      sessionStorage.setItem(APP_MARKER.storageKey, '1');
      sessionStorage.setItem(APP_MARKER.storageTimeKey, String(Date.now()));
      debug('tab marked via', reason, location.href);
    } catch {}
  }

  function hasRememberedMark() {
    try {
      if (sessionStorage.getItem(APP_MARKER.storageKey) !== '1') return false;

      const markedAt = Number(sessionStorage.getItem(APP_MARKER.storageTimeKey) || 0);
      return !markedAt || Date.now() - markedAt < APP_MARKER.ttlMs;
    } catch {
      return false;
    }
  }

  function isMarkedTab() {
    if (hasOrganizerMarker()) {
      if (!hasRememberedMark()) rememberMarkedTab('url/hash');
      return true;
    }

    return hasRememberedMark();
  }

  function cleanUrl(value) {
    let url = String(value || '').trim();
    if (!url) return '';

    url = url
      .replace(/&amp;/g, '&')
      .replace(/[),.;\]}]+$/g, '')
      .replace(/^["'<]+|[>"']+$/g, '');

    try {
      return new URL(url, location.href).href;
    } catch {
      return url;
    }
  }

  function isUsableImageUrl(url) {
    const lower = String(url || '').toLowerCase();
    if (!lower || lower.startsWith('data:')) return false;

    return (
      /\.(png|jpe?g|webp|gif)(\?|#|$)/i.test(lower) ||
      /mudae\.net\/uploads/i.test(lower) ||
      /cdn\.discordapp\.com|media\.discordapp\.net|discordapp\.com\/attachments/i.test(lower)
    );
  }

  function normalizeText(value) {
    return String(value || '')
      .normalize('NFKD')
      .replace(/[\u0300-\u036f]/g, '')
      .replace(/[{}()[\]_.:;~!?,+\-]+/g, ' ')
      .replace(/\s+/g, ' ')
      .trim()
      .toLowerCase();
  }

  function getSearchTargetName() {
    try {
      const url = new URL(location.href);
      if (!/\/search\/?$/i.test(url.pathname)) return '';
      if ((url.searchParams.get('type') || '').toLowerCase() !== 'character') return '';
      return String(url.searchParams.get('name') || '').trim();
    } catch {
      return '';
    }
  }

  function findCharacterResultLink(targetName) {
    const target = normalizeText(targetName);
    const links = Array.from(document.querySelectorAll('a[href*="/character/"]'));
    if (!links.length) return null;

    const candidates = links
      .map(link => {
        const href = link.getAttribute('href') || '';
        const text = normalizeText(link.textContent || link.getAttribute('title') || link.getAttribute('aria-label') || '');
        let url = null;
        try { url = new URL(href, location.href); } catch {}
        if (!url || !/\/character\/\d+/i.test(url.pathname)) return null;

        const pathName = normalizeText(decodeURIComponent(url.pathname.split('/').pop() || ''));
        let score = 1;
        if (target && text === target) score += 40;
        if (target && pathName === target) score += 35;
        if (target && text.includes(target)) score += 20;
        if (target && pathName.includes(target)) score += 18;
        if (/^https?:\/\/[^/]*mudae\.net$/i.test(url.origin)) score += 2;

        return { link, url, score };
      })
      .filter(Boolean)
      .sort((a, b) => b.score - a.score);

    return candidates[0] || null;
  }

  function maybeOpenSearchResult(attempt = 0) {
    if (copied || searchRedirecting || !isMarkedTab()) return false;

    const targetName = getSearchTargetName();
    if (!targetName) return false;

    const result = findCharacterResultLink(targetName);
    if (result?.url) {
      searchRedirecting = true;
      cleanup();
      info(`opening search result for "${targetName}"`);
      location.assign(result.url.href);
      return true;
    }

    if (attempt < TIMING.retryLimit) {
      clearTimeout(retryTimer);
      retryTimer = setTimeout(() => maybeOpenSearchResult(attempt + 1), TIMING.retryDelayMs);
    } else {
      debug(`marked search page but no character result was found for "${targetName}"`);
    }

    return true;
  }

  function getImagesRoot() {
    return document.querySelector('section#images') || document.getElementById('images');
  }

  function getCoverRoot() {
    return (
      document.querySelector('section#intro #cover') ||
      document.querySelector('section#intro img#cover') ||
      document.querySelector('section#intro .cover') ||
      document.getElementById('cover')
    );
  }

  function getActiveImageRoot() {
    const galleryRoot = getImagesRoot();
    if (galleryRoot) return { root: galleryRoot, mode: 'gallery' };

    const coverRoot = getCoverRoot();
    if (coverRoot) return { root: coverRoot, mode: 'cover' };

    return { root: null, mode: 'none' };
  }

  function imagesFromRoot(root, mode) {
    if (!root) return [];

    if (root.matches?.('img')) return [root];

    if (mode === 'cover') {
      return Array.from(root.querySelectorAll('img#cover, img.charimage, img'));
    }

    return Array.from(root.querySelectorAll('img.charimage, img'));
  }

  function getImageUrl(img) {
    return cleanUrl(
      img?.currentSrc ||
      img?.src ||
      img?.getAttribute?.('src') ||
      img?.getAttribute?.('data-src') ||
      img?.getAttribute?.('data-original') ||
      img?.getAttribute?.('data-lazy-src') ||
      ''
    );
  }

  function decodeHtmlAttribute(value) {
    return String(value || '')
      .replace(/&quot;/g, '"')
      .replace(/&#34;/g, '"')
      .replace(/&#39;/g, "'")
      .replace(/&amp;/g, '&');
  }

  function parseJsonAttribute(value, fallback) {
    const raw = String(value || '').trim();
    if (!raw) return fallback;

    try {
      return JSON.parse(raw);
    } catch {}

    try {
      return JSON.parse(decodeHtmlAttribute(raw));
    } catch {}

    return fallback;
  }

  function toNumber(value, fallback = null) {
    const number = Number(value);
    return Number.isFinite(number) ? number : fallback;
  }

  function normalizeMatch(match) {
    if (!match || typeof match !== 'object') return match;

    const output = { ...match };
    const rawImage = (
      output.url ||
      output.imageUrl ||
      output.src ||
      output.href ||
      output.link ||
      output.image ||
      output.filename ||
      output.file ||
      ''
    );

    if (typeof rawImage !== 'string' || !rawImage.trim()) return output;

    const raw = rawImage.trim().replace(/&amp;/g, '&').replace(/^["']+|["']+$/g, '');

    if (/^https?:\/\//i.test(raw)) {
      output.previewUrl = raw;
      return output;
    }

    if (/mudae\.net\/uploads/i.test(raw)) {
      output.previewUrl = raw.replace(/^\/+/g, 'https://');
      return output;
    }

    if (/\.(?:png|jpe?g|webp|gif)(?:[?#]|$)/i.test(raw)) {
      const ownerId = output.ownerId || output.userId || output.uploadId || output.upload || output.id || '';
      if (ownerId && /^\d+$/.test(String(ownerId))) {
        output.previewUrl = `https://mudae.net/uploads/${ownerId}/${raw.replace(/^\/+/g, '')}`;
      }
    }

    return output;
  }

  function readMatches(img) {
    const raw = img?.getAttribute?.('data-matches') || img?.dataset?.matches || '';
    if (!raw) return [];

    const parsed = parseJsonAttribute(raw, []);
    return Array.isArray(parsed) ? parsed.map(normalizeMatch) : [];
  }

  function readArrayAttribute(img, attrName) {
    const raw = img?.getAttribute?.(attrName) || '';
    if (!raw) return [];

    const parsed = parseJsonAttribute(raw, []);
    return Array.isArray(parsed) ? parsed : [];
  }

  function collectGalleryImages() {
    const { root, mode } = getActiveImageRoot();
    if (!root) return [];

    const images = [];
    const seenUrls = new Set();

    for (const img of imagesFromRoot(root, mode)) {
      const url = getImageUrl(img);
      if (!url || !isUsableImageUrl(url)) continue;

      const dedupeKey = url.replace(/[#?].*$/, '');
      if (seenUrls.has(dedupeKey)) continue;
      seenUrls.add(dedupeKey);

      const fallbackNumber = images.length + 1;
      const imageNumber = toNumber(img.getAttribute('data-number') || img.dataset?.number, fallbackNumber);
      const rating = toNumber(img.getAttribute('data-rating') || img.dataset?.rating, null);
      const matches = readMatches(img);

      images.push({
        index: imageNumber || fallbackNumber,
        number: imageNumber || fallbackNumber,
        url,
        id: img.getAttribute('data-id') || img.dataset?.id || '',
        name: img.getAttribute('data-name') || img.dataset?.name || '',
        matched: matches.length > 0,
        matches,
        rating,
        tags: readArrayAttribute(img, 'data-tags'),
        artist: readArrayAttribute(img, 'data-artist'),
        mode,
        source: 'mudae-gallery-copier-v1.0.2'
      });
    }

    return images;
  }

  function buildPayload(images) {
    return {
      type: 'mhp-mudae-gallery',
      version: 2,
      source: 'mudae-gallery-copier-v1.0.2',
      page: location.href,
      copiedAt: new Date().toISOString(),
      matchedCount: images.filter(image => image.matched).length,
      images
    };
  }

  async function copyText(text) {
    if (typeof GM_setClipboard === 'function') {
      GM_setClipboard(text, 'text');
      return true;
    }

    if (navigator.clipboard?.writeText) {
      await navigator.clipboard.writeText(text);
      return true;
    }

    const textarea = document.createElement('textarea');
    textarea.value = text;
    textarea.setAttribute('readonly', 'readonly');
    textarea.style.position = 'fixed';
    textarea.style.left = '-9999px';
    document.body.appendChild(textarea);
    textarea.select();

    const copiedText = document.execCommand('copy');
    textarea.remove();
    return copiedText;
  }

  function cleanup() {
    clearTimeout(retryTimer);
    retryTimer = null;

    try { documentObserver?.disconnect(); } catch {}
    try { imageObserver?.disconnect(); } catch {}

    documentObserver = null;
    imageObserver = null;
  }

  function closeHelperTab() {
    setTimeout(() => {
      try { window.close(); } catch {}

      setTimeout(() => {
        try {
          if (!document.hidden) location.replace('about:blank');
        } catch {}
      }, TIMING.fallbackBlankDelayMs);
    }, TIMING.closeDelayMs);
  }

  async function tryCopy(attempt = 0) {
    if (copied || !isMarkedTab()) return;
    if (maybeOpenSearchResult(0)) return;

    const images = collectGalleryImages();

    if (!images.length) {
      if (attempt < TIMING.retryLimit) {
        clearTimeout(retryTimer);
        retryTimer = setTimeout(() => tryCopy(attempt + 1), TIMING.retryDelayMs);
      } else {
        debug('marked tab but no gallery/cover image was found after retries');
      }
      return;
    }

    copied = true;
    cleanup();

    try {
      const payload = buildPayload(images);
      await copyText(JSON.stringify(payload));
      info(`copied ${images.length} images, ${payload.matchedCount} matched`);
      closeHelperTab();
    } catch (error) {
      copied = false;
      info('copy failed', error);
    }
  }

  function scheduleCopy(delay = 0) {
    if (copied || pendingTry || !isMarkedTab()) return;

    pendingTry = true;
    setTimeout(() => {
      pendingTry = false;
      tryCopy(0);
    }, delay);
  }

  function start(reason) {
    if (!isMarkedTab()) return;

    debug('active on marked tab:', reason, location.href);
    if (maybeOpenSearchResult(0)) return;
    scheduleCopy(TIMING.firstTryDelayMs);
    setTimeout(() => scheduleCopy(0), 300);
    setTimeout(() => scheduleCopy(0), 700);
    setTimeout(() => scheduleCopy(0), 1200);
  }

  function observeDom() {
    if (documentObserver) return;

    function attachObserver() {
      if (!document.documentElement) {
        setTimeout(attachObserver, 30);
        return;
      }

      documentObserver = new MutationObserver(() => {
        if (copied || !isMarkedTab()) return;

        const { root } = getActiveImageRoot();
        if (!root) return;

        scheduleCopy(30);

        try { documentObserver.disconnect(); } catch {}
        documentObserver = null;

        if (!imageObserver) {
          imageObserver = new MutationObserver(() => scheduleCopy(30));
          imageObserver.observe(root, {
            childList: true,
            subtree: true,
            attributes: true,
            attributeFilter: ['src', 'data-src', 'data-matches']
          });
        }
      });

      documentObserver.observe(document.documentElement, { childList: true, subtree: true });
    }

    attachObserver();
  }

  function watchRouteChanges() {
    setInterval(() => {
      if (location.href === lastHref) return;

      lastHref = location.href;
      copied = false;
      searchRedirecting = false;
      cleanup();
      start('route-change');
      observeDom();
    }, TIMING.routeCheckMs);
  }

  if (hasOrganizerMarker()) rememberMarkedTab('initial-url-or-hash');

  start('document-start');
  observeDom();
  watchRouteChanges();

  window.addEventListener('hashchange', () => start('hashchange'));
  window.addEventListener('DOMContentLoaded', () => start('DOMContentLoaded'));
  window.addEventListener('load', () => start('load'));
})();
